"use client";

import { useEffect, useState } from "react";
import ThemeSwitch from "../components/theme-switch";

function PencilLoader() {
  return <div className="pencil-loader-screen" role="status" aria-label="Loading portfolio"><div className="pencil-loader-wrap"><div className="pencil-loader-art"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" className="pencil"><defs><clipPath id="pencil-eraser"><rect height="30" width="30" ry="5" /></clipPath></defs><circle transform="rotate(-113,100,100)" strokeLinecap="round" strokeDashoffset="439.82" strokeDasharray="439.82 439.82" strokeWidth="2" stroke="#d8d8d8" fill="none" r="70" className="pencil__stroke" /><g transform="translate(100,100)" className="pencil__rotate"><g fill="none"><circle transform="rotate(-90)" strokeDashoffset="402" strokeDasharray="402.12 402.12" strokeWidth="30" stroke="#5f7f6b" r="64" className="pencil__body1" /><circle transform="rotate(-90)" strokeDashoffset="465" strokeDasharray="464.96 464.96" strokeWidth="10" stroke="#91aa98" r="74" className="pencil__body2" /><circle transform="rotate(-90)" strokeDashoffset="339" strokeDasharray="339.29 339.29" strokeWidth="10" stroke="#3f5f4c" r="54" className="pencil__body3" /></g><g transform="rotate(-90) translate(49,0)" className="pencil__eraser"><g className="pencil__eraser-skew"><rect height="30" width="30" ry="5" fill="#91aa98" /><rect clipPath="url(#pencil-eraser)" height="30" width="5" fill="#718b7a" /><rect height="20" width="30" fill="#e7e7e4" /><rect height="20" width="15" fill="#bdbdb9" /><rect height="20" width="5" fill="#d3d3cf" /><rect height="2" width="30" y="6" fill="rgba(20,30,24,.2)" /><rect height="2" width="30" y="13" fill="rgba(20,30,24,.2)" /></g></g><g transform="rotate(-90) translate(49,-30)" className="pencil__point"><polygon points="15 0,30 30,0 30" fill="#d6b27a" /><polygon points="15 0,6 30,0 30" fill="#a77b4d" /><polygon points="15 0,20 10,10 10" fill="#202823" /></g></g></svg></div><span className="pencil-loader-label">drawing up portfolio</span></div></div>;
}

const skillGroups = [
  { title: "Technical", items: ["Java", "Python", "C", "SQL", "JavaScript / TypeScript", "Node.js", "Next.js", "Flask", "MySQL", "HTML", "CSS", "Git", "GitHub"] },
  { title: "Concepts", items: ["OOP", "DSA", "DBMS", "OS", "Computer Networks", "System Design", "SDLC", "Agile"] },
  { title: "Product & Business", items: ["Product Discovery", "Requirements Gathering", "User Stories", "Feature Prioritization", "User Journey Mapping", "Business Analysis"] },
  { title: "Tools", items: ["VS Code", "Excel", "Docker", "Puppeteer", "Vercel", "Postman"] },
];
const projects = [
  { title: "STUKO", type: "Study platform", text: "An all-in-one study tool designed around interests, personality, and a genuinely cute UI." },
  { title: "Community Map Platform", type: "Web platform", text: "A community-focused mapping project built to make local information easier to discover and explore." },
  { title: "EAMCET 2027", type: "Education platform", text: "A student-focused web project with data-driven tooling and an evolving 2027 exam experience." },
  { title: "Project 04", type: "Experiment", text: "A space for the next idea worth building." },
  { title: "Project 05", type: "Experiment", text: "More things are being designed, tested, and shipped." },
  { title: "Project 06", type: "Experiment", text: "The portfolio is still growing — so is the work." },
];

export default function Home() {
  const [ready, setReady] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => setReady(true), 1100); return () => window.clearTimeout(timer); }, []);
  if (!ready) return <PencilLoader />;
  return <main className="site-shell">
    <style>{`.about-section .section-label.about-heading{color:var(--text);font-weight:700}.about-section .about-intro,.about-section .about-grade,.about-section .about-statement,.leadership-content p{color:var(--text)}.about-section .about-intro{font-size:1.2rem;line-height:1.8}.about-section .about-statement{font-size:1.25rem;line-height:1.8}.about-section .about-grade{font-size:1.05rem}.leadership .mini-label{color:var(--accent);font-weight:700}.leadership-details{margin-top:18px;border-top:1px solid var(--line)}.leadership-details details{border-bottom:1px solid var(--line)}.leadership-details summary{list-style:none;cursor:pointer;display:flex;align-items:center;padding:22px 4px;color:var(--text)}.leadership-details summary::-webkit-details-marker{display:none}.leadership-details summary span{display:flex;flex-direction:column;gap:7px}.leadership-details summary strong{font-size:1.25rem;color:var(--text)}.leadership-details summary small{font:600 11px 'DM Mono',monospace;letter-spacing:.08em;color:var(--text)}.leadership-content{padding:0 4px 20px}.leadership-content p{font-size:1rem;line-height:1.8;max-width:760px}.skills-table{border-top:1px solid var(--line);border-bottom:1px solid var(--line);margin-top:32px}.skill-row{display:grid;grid-template-columns:190px 1fr;border-bottom:1px solid var(--line);min-height:78px}.skill-row:last-child{border-bottom:0}.skill-category{font-weight:700;color:var(--text);padding:24px 22px 24px 0;border-right:1px solid var(--line);display:flex;align-items:flex-start}.skill-items{display:flex;flex-wrap:wrap;gap:10px;padding:20px 0 20px 22px;align-content:center}.skill-chip{display:inline-flex;align-items:center;border:1px solid var(--line);border-radius:4px;padding:8px 12px;color:var(--text);background:var(--surface);font-size:.92rem;line-height:1.1}.skill-chip:hover{border-color:var(--accent)}@media(max-width:700px){.skill-row{grid-template-columns:1fr}.skill-category{border-right:0;border-bottom:1px solid var(--line);padding:18px 0 12px}.skill-items{padding:16px 0}}`}</style>
    <nav className="nav"><a className="brand" href="#top">AB / 2026</a><div className="nav-links"><a href="#about">about</a><a href="#skills">skills</a><a href="#work">my work</a><a href="#contact">contact</a><ThemeSwitch /></div></nav>
    <section className="hero" id="top"><div className="hero-inner"><div className="eyebrow"><strong>ANJANI BEESU</strong></div><h1>Building things<br />worth clicking</h1><p className="hero-copy">CSE student&nbsp; | &nbsp;builder&nbsp; | &nbsp;curious human</p><div className="actions"><a className="button" href="#work">Explore my work ↗</a><a className="button primary" href="#contact">Connect with me ↗</a></div></div><div className="corner-note">SCROLL TO EXPLORE ↓</div></section>
    <section className="section about-section" id="about"><div className="section-label about-heading">01 / ABOUT ME</div><div className="about-content"><h2>Hi, I&apos;m Anjani Beesu.</h2><p className="about-intro">I&apos;m currently pursuing my <strong>B.Tech in Computer Science &amp; Engineering</strong>, where I&apos;m constantly exploring how technology can become something people genuinely enjoy using.</p><p className="about-grade"><strong>Grade: 9.15</strong></p><p className="about-statement">I build things that are intentional and useful.<br />I care about the details, the experience, and making every project feel like something worth clicking.</p><div className="leadership"><div className="mini-label">LEADERSHIP</div><div className="leadership-details"><details open><summary><span><strong>Class Representative</strong><small>AUG 2025 — PRESENT</small></span></summary><div className="leadership-content"><p>Serving as Class Representative for a class of 60, coordinating with faculty, managing class communication and academic requirements, and keeping things moving when they need to.</p></div></details><details open><summary><span><strong>Event Organizer</strong><small>4 DEPARTMENTAL + 1 COLLEGE-LEVEL EVENT</small></span></summary><div className="leadership-content"><p>Organized <strong>4 departmental events</strong> and <strong>1 college-level event</strong>, helping plan, coordinate, and execute events with students and faculty.</p></div></details></div></div></div></section>
    <section className="section" id="skills"><div className="section-label">02 / SKILLS</div><h2>Tools I build with.</h2><div className="skills-table">{skillGroups.map((group) => <div className="skill-row" key={group.title}><div className="skill-category">{group.title}</div><div className="skill-items">{group.items.map((item) => <span className="skill-chip" key={item}>{item}</span>)}</div></div>)}</div></section>
    <section className="section work-section" id="work"><div className="section-label">03 / MY WORK</div><h2>Things I&apos;ve built.</h2><div className="project-grid">{projects.map((project, index) => <article className="project-card" key={project.title}><span className="project-number">0{index + 1}</span><div><span className="project-type">{project.type}</span><h3>{project.title}</h3><p>{project.text}</p></div><span className="project-arrow">↗</span></article>)}</div></section>
    <section className="section contact-section" id="contact"><div className="section-label">04 / CONTACT ME</div><div className="contact-grid"><div><h2>Have an idea?<br />Send it my way.</h2><p>Whether it&apos;s an internship, collaboration, project, or simply an interesting conversation — I&apos;d love to hear from you.</p></div><form className="contact-form" action="/api/contact" method="POST"><label>Name<input name="name" type="text" placeholder="Your name" required /></label><label>Email<input name="email" type="email" placeholder="you@example.com" required /></label><label>Message<textarea name="message" placeholder="Tell me what&apos;s on your mind..." rows={5} required /></label><button className="button primary" type="submit">Send message ↗</button></form></div></section>
    <footer className="footer">© 2026 Anjani Beesu · designed &amp; built from scratch.</footer>
  </main>;
}
